2021-06-13 17:18:31,514 [main.py         | 48] INFO: Start to run instance_1
2021-06-13 17:18:31,514 [simulate_api.py | 60] INFO: Start time of the simulator: 2021-06-13 00:00:00, time interval:  600.00
2021-06-13 17:18:31,526 [input_utils.py  | 48] INFO: Get 154 factories
2021-06-13 17:18:33,127 [input_utils.py  | 52] INFO: Get 23562 routes
2021-06-13 17:18:33,154 [input_utils.py  | 57] INFO: Get 5 vehicles
2021-06-13 17:18:33,164 [input_utils.py  | 61] INFO: Get 50 orders
2021-06-13 17:18:33,164 [simulate_api.py | 87] INFO: Initial position of V_1 is e2d5093fbe36431f8986ddb0e1c586be
2021-06-13 17:18:33,167 [simulate_api.py | 87] INFO: Initial position of V_2 is 7fe14b93f0f04ee7a994ef5b2c1fdb72
2021-06-13 17:18:33,167 [simulate_api.py | 87] INFO: Initial position of V_3 is fa366fc87a124d32926daa5bb093129f
2021-06-13 17:18:33,167 [simulate_api.py | 87] INFO: Initial position of V_4 is e47399648fa842b2b8f80094343d8091
2021-06-13 17:18:33,167 [simulate_api.py | 87] INFO: Initial position of V_5 is becb4f85393540b287e7329758b8d832
2021-06-13 17:18:33,167 [simulate_environment.py | 96] INFO: **************************************************
2021-06-13 17:18:33,167 [simulate_environment.py | 100] INFO: cur time: 2021-06-13 00:10:00, pre time: 2021-06-13 00:00:00
2021-06-13 17:18:33,167 [simulate_environment.py | 136] INFO: Start to update the input of 2021-06-13 00:10:00
2021-06-13 17:18:33,168 [simulate_environment.py | 163] INFO: Get 1 unallocated order items, 0 ongoing order items, 0 completed order items
2021-06-13 17:18:34,257 [simulate_environment.py | 247] INFO: 2021-06-13 00:10:00, Item 0003480001-1: state = 1 < 2, we can not finish the simulation
2021-06-13 17:18:34,258 [simulate_environment.py | 96] INFO: **************************************************
2021-06-13 17:18:34,258 [simulate_environment.py | 100] INFO: cur time: 2021-06-13 00:20:00, pre time: 2021-06-13 00:10:00
2021-06-13 17:18:34,258 [simulate_environment.py | 136] INFO: Start to update the input of 2021-06-13 00:20:00
2021-06-13 17:18:34,274 [simulate_environment.py | 163] INFO: Get 3 unallocated order items, 0 ongoing order items, 0 completed order items
2021-06-13 17:18:35,208 [simulate_environment.py | 240] ERROR: 2021-06-13 17:18:35,143 [main_algorithm.py | 32] ERROR: Failed to run algorithm
2021-06-13 17:18:35,144 [main_algorithm.py | 33] ERROR: Error: 'vehicle' object has no attribute 'gen_fix_route', Traceback (most recent call last):
  File "main_algorithm.py", line 29, in <module>
    scheduling()
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\vrppd\main_algorithm.py", line 237, in scheduling
    time_2_go = pushVehicle2Solver(vehicles_info, dvrppd_Solver, customer_id_info_map, ongoing_items_map, request_info)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\vrppd\main_algorithm.py", line 213, in pushVehicle2Solver
    dvrppd_Solver.getVehiclesPool[vehicleID].gen_fix_route(dvrppd_Solver.getCustomerPool,
AttributeError: 'vehicle' object has no attribute 'gen_fix_route'

FAIL

2021-06-13 17:18:35,208 [main.py         | 55] ERROR: Failed to run simulator
2021-06-13 17:18:35,208 [main.py         | 56] ERROR: Error: 未寻获算法输出成功标识SUCCESS, Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/dpdp/simulator/dpdp_competition/main.py", line 51, in <module>
    score = simulate(Configs.factory_info_file, Configs.route_info_file, instance)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_api.py", line 94, in simulate
    simulate_env.run()
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_environment.py", line 107, in run
    used_seconds, dispatch_result = self.dispatch(updated_input_info)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_environment.py", line 241, in dispatch
    raise ValueError('未寻获算法输出成功标识SUCCESS')
ValueError: 未寻获算法输出成功标识SUCCESS

