2021-06-13 17:20:16,750 [main.py         | 48] INFO: Start to run instance_1
2021-06-13 17:20:16,750 [simulate_api.py | 60] INFO: Start time of the simulator: 2021-06-13 00:00:00, time interval:  600.00
2021-06-13 17:20:16,762 [input_utils.py  | 48] INFO: Get 154 factories
2021-06-13 17:20:18,337 [input_utils.py  | 52] INFO: Get 23562 routes
2021-06-13 17:20:18,364 [input_utils.py  | 57] INFO: Get 5 vehicles
2021-06-13 17:20:18,372 [input_utils.py  | 61] INFO: Get 50 orders
2021-06-13 17:20:18,373 [simulate_api.py | 87] INFO: Initial position of V_1 is e2d5093fbe36431f8986ddb0e1c586be
2021-06-13 17:20:18,376 [simulate_api.py | 87] INFO: Initial position of V_2 is 7fe14b93f0f04ee7a994ef5b2c1fdb72
2021-06-13 17:20:18,376 [simulate_api.py | 87] INFO: Initial position of V_3 is fa366fc87a124d32926daa5bb093129f
2021-06-13 17:20:18,376 [simulate_api.py | 87] INFO: Initial position of V_4 is e47399648fa842b2b8f80094343d8091
2021-06-13 17:20:18,376 [simulate_api.py | 87] INFO: Initial position of V_5 is becb4f85393540b287e7329758b8d832
2021-06-13 17:20:18,377 [simulate_environment.py | 96] INFO: **************************************************
2021-06-13 17:20:18,377 [simulate_environment.py | 100] INFO: cur time: 2021-06-13 00:10:00, pre time: 2021-06-13 00:00:00
2021-06-13 17:20:18,377 [simulate_environment.py | 136] INFO: Start to update the input of 2021-06-13 00:10:00
2021-06-13 17:20:18,378 [simulate_environment.py | 163] INFO: Get 1 unallocated order items, 0 ongoing order items, 0 completed order items
2021-06-13 17:20:19,469 [simulate_environment.py | 240] ERROR: 2021-06-13 00:20:00
{'0003480001': {'pallets': {'q_standard': 0, 'q_small': 0.5, 'q_box': 0}, 'demand': 0.5, 'creation_time': '2021-06-13 00:03:48', 'pickup_timeWindow': ['2021-06-13 00:03:48', '2021-06-13 04:03:48'], 'delivery_timeWindow': ['2021-06-13 00:03:48', '2021-06-13 04:03:48'], 'load/unload_time': 120, 'pickup_customer_id': '2445d4bd004c457d95957d6ecf77f759', 'delivery_customer_id': 'b6dd694ae05541dba369a2a759d2c2b9'}}
['0003480001']
vehicleID:  V_5 requestID:  0 demandType:   depot customerID:  becb4f85393540b287e7329758b8d832      arrive_time: 2021-06-13 00:20:00 leave_time: 2021-06-13 00:20:00
vehicleID:  V_5 requestID:  0003480001 demandType:   pickup customerID:  2445d4bd004c457d95957d6ecf77f759      arrive_time: 2021-06-13 00:35:24 leave_time: 2021-06-13 01:07:24 travel_time:  15.4 dis:  7.7
vehicleID:  V_5 requestID:  0003480001 demandType:   delivery customerID:  b6dd694ae05541dba369a2a759d2c2b9      arrive_time: 2021-06-13 02:07:24 leave_time: 2021-06-13 02:39:24 travel_time:  60.0 dis:  12.0
score is: 19.7
customerID is: 2445d4bd004c457d95957d6ecf77f759 port ID is: 0 [vehicleID is: V_5 requestID is  0003480001    arrive_time is: 2021-06-13 00:35:24 leave_time is: 2021-06-13 01:07:24 ] 
customerID is: b6dd694ae05541dba369a2a759d2c2b9 port ID is: 0 [vehicleID is: V_5 requestID is  0003480001    arrive_time is: 2021-06-13 02:07:24 leave_time is: 2021-06-13 02:39:24 ] 
2021-06-13 17:20:19,406 [main_algorithm.py | 32] ERROR: Failed to run algorithm
2021-06-13 17:20:19,406 [main_algorithm.py | 33] ERROR: Error: list assignment index out of range, Traceback (most recent call last):
  File "main_algorithm.py", line 29, in <module>
    scheduling()
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\vrppd\main_algorithm.py", line 244, in scheduling
    data_transfomer.__solution_algo_2_sim(vehicle_route,
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\data_transfomer\data_transfomer.py", line 249, in __solution_algo_2_sim
    del vehicle_route[vehicleID][0]
IndexError: list assignment index out of range

FAIL

2021-06-13 17:20:19,470 [main.py         | 55] ERROR: Failed to run simulator
2021-06-13 17:20:19,470 [main.py         | 56] ERROR: Error: 未寻获算法输出成功标识SUCCESS, Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/dpdp/simulator/dpdp_competition/main.py", line 51, in <module>
    score = simulate(Configs.factory_info_file, Configs.route_info_file, instance)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_api.py", line 94, in simulate
    simulate_env.run()
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_environment.py", line 107, in run
    used_seconds, dispatch_result = self.dispatch(updated_input_info)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_environment.py", line 241, in dispatch
    raise ValueError('未寻获算法输出成功标识SUCCESS')
ValueError: 未寻获算法输出成功标识SUCCESS

